# In this document we can see the different configurations of the evaluation pipeline.
# The microservices are order by their operating order.

pipeline_executor:
  _target_: src.PipelineExecutor
  _partial_: True
  input_dir: videos
  pipeline_type: evaluation
  is_input_data_in_folder: True