# In this document we can see the different configurations of the training pipeline.
# The microservices are order by their operating order.

pipeline_executor:
  _target_: src.pipline_executor.PipelineExecutor
  _partial_: True
  input_dir: text
  pipeline_type: training
  is_input_data_in_folder: True


text_parsers:
 text_parser_n_threads: 1
 text_parser:
     _target_: src.micro_services.text_counter.TextCounter
     arg1: 1
     arg2: 2




