_target_: src.training.hyperparameters_tuning.classification.random_forest.RandomForestStudy
sampler:
  _target_: optuna.samplers.TPESampler
  n_startup_trials: 1
  seed: 42
feature_type: text
seed: 42
direction: maximize
optimize_metric: f1_macro
n_trials: 2
n_jobs: 1
n_jobs_forest: -1
cv:
  _target_: src.training.train_val_splitters.text_size_train_val_splitter.TextSizeTrainValSplitter