_target_: src.training.data_loaders.text_size_data_loader.TextSizeDataLoader
pipeline_type: training
seed: 42
labels_path: # add path for labels for real data
split_data: true
load_train: true
load_test: true
load_predict: False
